app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

use Illuminate\Http\Request;

Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix'=>'admin','as'=>'admin.','middleware'=>'auth.checkrole:admin'],function (){
    Route::get('categories', ['uses'=>'CategoriesController@index','as'=>'categories.index']);
    Route::get('categories/create', ['uses'=>'CategoriesController@create','as'=>'categories.create']);
    Route::post('categories/store', ['uses'=>'CategoriesController@store','as'=>'categories.store']);
    Route::get('categories/edit/{id}', ['uses'=>'CategoriesController@edit','as'=>'categories.edit']);
    Route::post('categories/update/{id}', ['uses'=>'CategoriesController@update','as'=>'categories.update']);
    Route::get('categories/destroy/{id}', ['uses'=>'CategoriesController@destroy','as'=>'categories.destroy']);

    Route::get('products', ['uses'=>'ProductsController@index','as'=>'products.index']);
    Route::get('products/create', ['uses'=>'ProductsController@create','as'=>'products.create']);
    Route::post('products/store', ['uses'=>'ProductsController@store','as'=>'products.store']);
    Route::get('products/edit/{id}', ['uses'=>'ProductsController@edit','as'=>'products.edit']);
    Route::post('products/update/{id}', ['uses'=>'ProductsController@update','as'=>'products.update']);
    Route::get('products/destroy/{id}', ['uses'=>'ProductsController@destroy','as'=>'products.destroy']);

    Route::get('clients', ['uses'=>'ClientsController@index','as'=>'clients.index']);
    Route::get('clients/create', ['uses'=>'ClientsController@create','as'=>'clients.create']);
    Route::post('clients/store', ['uses'=>'ClientsController@store','as'=>'clients.store']);
    Route::get('clients/edit/{id}', ['uses'=>'ClientsController@edit','as'=>'clients.edit']);
    Route::post('clients/update/{id}', ['uses'=>'ClientsController@update','as'=>'clients.update']);
    Route::get('clients/destroy/{id}', ['uses'=>'ClientsController@destroy','as'=>'clients.destroy']);

    Route::get('orders', ['uses'=>'OrdersController@index','as'=>'orders.index']);
    Route::get('orders/{id}', ['uses'=>'OrdersController@edit','as'=>'orders.edit']);
    Route::post('orders/{id}', ['uses'=>'OrdersController@update','as'=>'orders.update']);

    Route::get('cupoms', ['uses'=>'CupomsController@index','as'=>'cupoms.index']);
    Route::get('cupoms/create', ['uses'=>'CupomsController@create','as'=>'cupoms.create']);
    Route::post('cupoms/store', ['uses'=>'CupomsController@store','as'=>'cupoms.store']);
});

Route::group(['prefix'=>'customer','middleware'=>'auth.checkrole:client','as'=>'customer.'], function (){
    Route::get('orders',['uses'=>'CheckoutController@index','as'=>'orders.index']);
    Route::get('orders/create',['uses'=>'CheckoutController@create','as'=>'orders.create']);
    Route::post('orders/store',['uses'=>'CheckoutController@store','as'=>'orders.store']);
});

Route::group(['middleware'=>'cors'],function (){

    Route::post('oauth/access_token', function() {
        return Response::json(Authorizer::issueAccessToken());
    });

    Route::group(['prefix'=>'api','middleware'=>'oauth','as'=>'api.'], function (){
        Route::group(['prefix'=>'client','middleware'=>'oauth.checkrole:client','as'=>'client.'], function () {
            Route::resource('orders', 'Api\Client\ClientCheckoutController', ['except'=> ['create','edit','destroy']]);
            Route::get('products','Api\Client\ClientProductController@index');
        });

        Route::group(['prefix'=>'deliveryman','middleware'=>'oauth.checkrole:deliveryman','as'=>'deliveryman.'], function () {
            Route::resource('orders', 'Api\Deliveryman\DeliverymanCheckoutController', ['except'=> ['create','edit','destroy']]);
            Route::patch('orders/{id}/update-status',[
                'uses'=>'Api\Deliveryman\DeliverymanCheckoutController@updateStatus','as'=>'orders.update_status'
            ]);
        });

        Route::get('authenticated',['uses' => 'Api\UserController@getAuthenticatedUser', 'as' => 'user.authenticated']);
    });

    Route::group(['prefix'=>'api','as'=>'api.'], function (){
        Route::post('/register',['uses' => 'Api\UserController@registerUser', 'as' => 'user.register']);
        Route::post('/password-reminder',['uses' => 'Api\UserController@sendPasswordResetToken', 'as'=> 'user.password-reminder']);
        Route::post('/password-reset',['uses' => 'Api\UserController@resetPassword', 'as'=> 'user.password-reset']);
    });
    
});

app/Models/Order.php
<?php

namespace CodeDelivery\Models;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Order extends Model implements Transformable
{
    use TransformableTrait;

    protected $fillable = [
        'client_id',
        'user_deliveryman_id',
        'total',
        'status',
        'cupom_id'
    ];

    protected $hidden = array('pivot');

    public function transform()
    {
        return [
            'order' => $this->id,
            'order_items' => $this->items
        ];
    }

    public function items()
    {
        return $this->hasMany(OrderItem::class);
    }

    public function deliveryman()
    {
        return $this->belongsTo(User::class,'user_deliveryman_id');
    }

    public function client()
    {
        return $this->belongsTo(Client::class);
    }

    public function cupom()
    {
        return $this->belongsTo(Cupom::class);
    }

}

app/Http/Controllers/OrdersController.php
<?php

namespace CodeDelivery\Http\Controllers;

use CodeDelivery\Http\Requests\AdminOrderRequest;
use CodeDelivery\Repositories\OrderRepository;
use CodeDelivery\Http\Requests;
use CodeDelivery\Repositories\UserRepository;

class OrdersController extends Controller
{
    private $orderRepository;

    public function __construct(OrderRepository $orderRepository)
    {
        $this->orderRepository = $orderRepository;
    }

    public function index()
    {
        $orders = $this->orderRepository->paginate();
        return view('admin.orders.index',compact('orders'));
    }
    
    public function edit($id, UserRepository $userRepository)
    {
        $order = $this->orderRepository->find($id);
        $list_status = [ 0 => 'Pendente', 1 => 'A caminho', 2 => 'Entregue', 3 => 'Cancelado']; //todo criar tabela
        $list_deliveries = $userRepository->findWhere(['role'=>'deliveryman'])->lists('name','id');
        return view('admin.orders.edit',compact('order','list_status','list_deliveries'));
    }
    
    public function update(AdminOrderRequest $request,$id)
    {
        $data = $request->all();
        $this->orderRepository->update($data,$id);
        return redirect()->route('admin.orders.index');
    }
}

resources/views/customer/orders/create.blade.php
@extends('app')

@section('content')
    <div class="container">
        <h3>Novo pedido</h3>
        </br>

        @include('errors._check')

        <div class="container">
            {!! Form::open(['route'=>'customer.orders.store','class'=>'form']) !!}

            <div class="form-group">
                <label>Total: </label>
                <p id="total"></p>
                <a href="#"id="btn-new-item" class="btn btn-default">Novo item</a>
                </br></br>

                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <td>Produto</td>
                            <td>Quantidade</td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <select class="form-control" name="items[0][product_id]">
                                    @foreach($products as $product)
                                        <option value="{{$product->id}}" data-price="{{$product->price}}">{{$product->name}} --- {{$product->price}}</option>
                                    @endforeach
                                </select>
                            </td>
                            <td>
                                {!! Form::text('items[0][amount]',1,['class'=>'form-control']) !!}
                            </td>
                        </tr>
                    </tbody>
                    <input type="hidden" value="teste" name="teste">
                </table>
            </div>


            <div class="form-group">
                {!! Form::submit('Fechar pedido',['class'=>'btn btn-primary']) !!}
            </div>
            {!! Form::close() !!}
        </div>

    </div>
@endsection

@section('post-script')
    <script>
        $('#btn-new-item').click(function () {
            var row = $('table tbody > tr:last');
            var new_row = row.clone();
            var length = $('table tbody tr').length;

            new_row.find('td').each(function () {
                var td = $(this);
                var input = td.find('input,select');
                var name = input.attr('name');

                input.attr('name', name.replace((length - 1) + "", length + ""));
            });

            new_row.find('input').val(1);
            new_row.insertAfter(row);
        });

        $(document.body).on('click','select',function () {
            calculateTotal();
        });

        $(document.body).on('blur','input',function () {
            calculateTotal();
        });

        function calculateTotal() {
            var total = 0;
            var rows = $('table tbody tr');
            var row = null, price, amount;

            for (var i = 0; i < rows.length; i++) {
                row = rows.eq(i);
                price = row.find(':selected').data('price');
                amount = row.find('input').val();
                total += price * amount;
            }

            $('#total').html(total);
        }
    </script>
@endsection

resources/views/customer/orders/index.blade.php
@extends('app')

@section('content')
    <div class="container">
        <h3>Meus pedidos</h3>

        <a href="{{route('customer.orders.create')}}" class="btn btn-default">Novo pedido</a>
        <br><br>

        <table class="table table-bordered">
            <thead>
            <tr>
                <th>ID</th>
                <th>Total</th>
                <th>Status</th>
            </tr>
            </thead>

            <tbody>
            @foreach($orders as $order)
                <tr>
                    <td>#{{ $order->id }}</td>
                    <td>R$ {{ $order->total }}</td>
                    <td> {{ $order->status }}</td>
                </tr>
            @endforeach
            </tbody>
        </table>

        {!! $orders->render() !!}
    </div>
@endsection