app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

use Illuminate\Http\Request;

Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix'=>'admin','as'=>'admin.','middleware'=>'auth.checkrole:admin'],function (){
    Route::get('categories', ['uses'=>'CategoriesController@index','as'=>'categories.index']);
    Route::get('categories/create', ['uses'=>'CategoriesController@create','as'=>'categories.create']);
    Route::post('categories/store', ['uses'=>'CategoriesController@store','as'=>'categories.store']);
    Route::get('categories/edit/{id}', ['uses'=>'CategoriesController@edit','as'=>'categories.edit']);
    Route::post('categories/update/{id}', ['uses'=>'CategoriesController@update','as'=>'categories.update']);
    Route::get('categories/destroy/{id}', ['uses'=>'CategoriesController@destroy','as'=>'categories.destroy']);

    Route::get('products', ['uses'=>'ProductsController@index','as'=>'products.index']);
    Route::get('products/create', ['uses'=>'ProductsController@create','as'=>'products.create']);
    Route::post('products/store', ['uses'=>'ProductsController@store','as'=>'products.store']);
    Route::get('products/edit/{id}', ['uses'=>'ProductsController@edit','as'=>'products.edit']);
    Route::post('products/update/{id}', ['uses'=>'ProductsController@update','as'=>'products.update']);
    Route::get('products/destroy/{id}', ['uses'=>'ProductsController@destroy','as'=>'products.destroy']);

    Route::get('clients', ['uses'=>'ClientsController@index','as'=>'clients.index']);
    Route::get('clients/create', ['uses'=>'ClientsController@create','as'=>'clients.create']);
    Route::post('clients/store', ['uses'=>'ClientsController@store','as'=>'clients.store']);
    Route::get('clients/edit/{id}', ['uses'=>'ClientsController@edit','as'=>'clients.edit']);
    Route::post('clients/update/{id}', ['uses'=>'ClientsController@update','as'=>'clients.update']);
    Route::get('clients/destroy/{id}', ['uses'=>'ClientsController@destroy','as'=>'clients.destroy']);

    Route::get('orders', ['uses'=>'OrdersController@index','as'=>'orders.index']);
    Route::get('orders/{id}', ['uses'=>'OrdersController@edit','as'=>'orders.edit']);
    Route::post('orders/{id}', ['uses'=>'OrdersController@update','as'=>'orders.update']);

    Route::get('cupoms', ['uses'=>'CupomsController@index','as'=>'cupoms.index']);
    Route::get('cupoms/create', ['uses'=>'CupomsController@create','as'=>'cupoms.create']);
    Route::post('cupoms/store', ['uses'=>'CupomsController@store','as'=>'cupoms.store']);
});

Route::group(['prefix'=>'customer','middleware'=>'auth.checkrole:client','as'=>'customer.'], function (){
    Route::get('orders',['uses'=>'CheckoutController@index','as'=>'orders.index']);
    Route::get('orders/create',['uses'=>'CheckoutController@create','as'=>'orders.create']);
    Route::post('orders/store',['uses'=>'CheckoutController@store','as'=>'orders.store']);
});

Route::group(['middleware'=>'cors'],function (){

    Route::post('oauth/access_token', function() {
        return Response::json(Authorizer::issueAccessToken());
    });

    Route::group(['prefix'=>'api','middleware'=>'oauth','as'=>'api.'], function (){
        Route::group(['prefix'=>'client','middleware'=>'oauth.checkrole:client','as'=>'client.'], function () {
            Route::resource('orders', 'Api\Client\ClientCheckoutController', ['except'=> ['create','edit','destroy']]);
            Route::get('products','Api\Client\ClientProductController@index');
        });

        Route::group(['prefix'=>'deliveryman','middleware'=>'oauth.checkrole:deliveryman','as'=>'deliveryman.'], function () {
            Route::resource('orders', 'Api\Deliveryman\DeliverymanCheckoutController', ['except'=> ['create','edit','destroy']]);
            Route::patch('orders/{id}/update-status',[
                'uses'=>'Api\Deliveryman\DeliverymanCheckoutController@updateStatus','as'=>'orders.update_status'
            ]);
        });

        Route::get('authenticated',['uses' => 'Api\UserController@getAuthenticatedUser', 'as' => 'user.authenticated']);
    });

    Route::group(['prefix'=>'api','as'=>'api.'], function (){
        Route::post('/register',['uses' => 'Api\UserController@registerUser', 'as' => 'user.register']);
        Route::post('/password-reminder',['uses' => 'Api\UserController@sendPasswordResetToken', 'as'=> 'user.password-reminder']);
        Route::post('/password-reset',['uses' => 'Api\UserController@resetPassword', 'as'=> 'user.password-reset']);
    });
    
});

app/Models/Client.php
<?php

namespace CodeDelivery\Models;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Client extends Model implements Transformable
{
    use TransformableTrait;

    protected $fillable = [
        'user_id',
        'phone',
        'address',
        'city',
        'state',
        'zipcode'
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function orders()
    {
        return $this->hasMany(Order::class);
    }

}

app/Http/Controllers/Api/Client/ClientCheckoutController.php
<?php

namespace CodeDelivery\Http\Controllers\Api\Client;

use CodeDelivery\Http\Controllers\Controller;
use CodeDelivery\Http\Requests\CheckoutRequest;
use CodeDelivery\Http\Requests\CustomerOrderRequest;
use CodeDelivery\Http\Requests;
use CodeDelivery\Repositories\OrderRepository;
use CodeDelivery\Repositories\UserRepository;
use CodeDelivery\Services\OrderService;
use LucaDegasperi\OAuth2Server\Facades\Authorizer;

class ClientCheckoutController extends Controller
{
    private $orderRepository;
    private $userRepository;
    private $orderService;

    private $relationships = ['cupom','items','client'];

    public function __construct(
            OrderRepository $orderRepository,
            UserRepository $userRepository,
            OrderService $orderService)
    {
        $this->orderRepository = $orderRepository;
        $this->userRepository = $userRepository;
        $this->orderService = $orderService;
    }

    public function index()
    {
        $user_id = Authorizer::getResourceOwnerId();
        $client_id = $this->userRepository->find($user_id)->client->id;
        $orders = $this->orderRepository
            ->skipPresenter(false)
            ->with($this->relationships)
            ->scopeQuery(function ($query) use ($client_id) {
            return $query->where('client_id','=',$client_id);
        })->paginate();
        return $orders;
    }

    public function store(CheckoutRequest $request)
    {
        $data = $request->all();
        $user_id = Authorizer::getResourceOwnerId();
        $client_id = $this->userRepository->find($user_id)->client->id;
        $data['client_id'] = $client_id;
        $order = $this->orderService->create($data);
        return $this->orderRepository
            ->skipPresenter(false)
            ->with($this->relationships)
            ->find($order->id);
    }
    
    public function show($id)
    {
        return $this->orderRepository
            ->skipPresenter(false)
            ->with($this->relationships)
            ->find($id);
    }
}

app/Http/Controllers/Api/Client/ClientProductController.php
<?php

namespace CodeDelivery\Http\Controllers\Api\Client;

use CodeDelivery\Http\Controllers\Controller;
use CodeDelivery\Http\Requests\CheckoutRequest;
use CodeDelivery\Http\Requests\CustomerOrderRequest;
use CodeDelivery\Http\Requests;
use CodeDelivery\Repositories\OrderRepository;
use CodeDelivery\Repositories\ProductRepository;
use CodeDelivery\Repositories\UserRepository;
use CodeDelivery\Services\OrderService;
use LucaDegasperi\OAuth2Server\Facades\Authorizer;

class ClientProductController extends Controller
{
    private $relationships = [];

    /**
     * @var ProductRepository
     */
    private $repository;

    public function __construct(ProductRepository $repository)
    {
        $this->repository = $repository;
    }

    public function index()
    {
        $products = $this->repository
            ->skipPresenter(false)
            ->with($this->relationships)
            ->all();
        return $products;
    }

    public function show($id)
    {
        return $this->repository
            ->skipPresenter(false)
            ->with($this->relationships)
            ->find($id);
    }
}

app/Http/Controllers/ClientsController.php
<?php

namespace CodeDelivery\Http\Controllers;

use CodeDelivery\Http\Requests\AdminClientRequest;
use CodeDelivery\Repositories\ClientRepository;
use CodeDelivery\Http\Requests;
use CodeDelivery\Repositories\UserRepository;
use CodeDelivery\Services\ClientService;

class ClientsController extends Controller
{
    private $clientRepository;
    private $userRepository;
    private $clientService;

    public function __construct(ClientRepository $clientRepository, UserRepository $userRepository, ClientService $clientService)
    {
        $this->clientRepository = $clientRepository;
        $this->userRepository = $userRepository;
        $this->clientService = $clientService;
    }

    public function index()
    {
        $clients = $this->clientRepository->paginate();
        return view('admin.clients.index',compact('clients'));
    }

    public function create()
    {
        return view('admin.clients.create');
    }
    
    public function store(AdminClientRequest $request)
    {
        $data = $request->all();
        $this->clientService->create($data);
        return redirect()->route('admin.clients.index');
    }
    
    public function edit($id)
    {
        $client = $this->clientRepository->with('user')->find($id);
        return view('admin.clients.edit',compact('client'));
    }

    public function update(AdminClientRequest $request,$id)
    {
        $data = $request->all();
        $this->clientService->update($data,$id);
        return redirect()->route('admin.clients.index');
    }

    public function destroy($id)
    {
        $response = $this->clientService->destroy($id);
        $redirect = redirect()->route('admin.clients.index');
        if (!$response['error']) {
            $redirect->with('message',$response['message']);
        } else {
            $redirect->with('error',$response['message']);
        }
        return $redirect;
    } 
}

resources/views/admin/clients/_form.blade.php
<div class="form-group">
    {!! Form::label('user[name]','Nome:') !!}
    {!! Form::text('user[name]', null, ['class'=>'form-control']) !!}
    {!! Form::label('user[email]','Email:') !!}
    {!! Form::email('user[email]', null, ['class'=>'form-control']) !!}
    {!! Form::label('phone','Telefone:') !!}
    {!! Form::text('phone', null, ['class'=>'form-control']) !!}
    {!! Form::label('address','Endereço:') !!}
    {!! Form::text('address', null, ['class'=>'form-control']) !!}
    {!! Form::label('city','Cidade:') !!}
    {!! Form::text('city', null, ['class'=>'form-control']) !!}
    {!! Form::label('state','Estado:') !!}
    {!! Form::text('state', null, ['class'=>'form-control']) !!}
    {!! Form::label('zipcode','CEP:') !!}
    {!! Form::text('zipcode', null, ['class'=>'form-control']) !!}
</div>

resources/views/admin/clients/create.blade.php
@extends('app')

@section('content')
    <div class="container">
        <h3>Novo cliente</h3>

        @include('errors._check')

        {!! Form::open(['route'=>'admin.clients.store']) !!}

        @include('admin.clients._form')

        <div class="form-group">
            {!! Form::submit('Criar cliente',['class'=>'btn btn-primary']) !!}
        </div>

        {!! Form::close() !!}
    </div>
@endsection

resources/views/admin/clients/edit.blade.php
@extends('app')

@section('content')
    <div class="container">
        <h3>Editando cliente: {{ $client->user->name }}</h3>

        @include('errors._check')

        {!! Form::model($client->toArray(),['route'=>['admin.clients.update', $client->id]]) !!}

        @include('admin.clients._form')

        <div class="form-group">
            {!! Form::submit('Salvar cliente',['class'=>'btn btn-primary']) !!}
        </div>

        {!! Form::close() !!}
    </div>
@endsection

resources/views/admin/clients/index.blade.php
@extends('app')

@section('content')
    <div class="container">
        <h3>Clientes</h3>
        @include('messages._check')
        <br>
        <a href="{{ route('admin.clients.create') }}" class="btn btn-default">Novo cliente</a>
        <br>
        <br>
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>ID</th>
                <th>Nome</th>
                <th>Email</th>
                <th>Telefone</th>
                <th>Endereço</th>
                <th>Cidade</th>
                <th>Estado</th>
                <th>Ação</th>
            </tr>
            </thead>
            <tbody>
            @foreach($clients as $client)
                <tr>
                    <td>{{ $client->id }}</td>
                    <td>{{ $client->user->name }}</td>
                    <td>{{ $client->user->email }}</td>
                    <td>{{ $client->phone }}</td>
                    <td>{{ $client->address }}</td>
                    <td>{{ $client->city }}</td>
                    <td>{{ $client->state }}</td>
                    <td>
                        <a href="{{ route('admin.clients.edit',['id'=>$client->id]) }}" class="btn btn-default btn-small">Editar</a>
                        <a href="{{ route('admin.clients.destroy',['id'=>$client->id]) }}" class="btn btn-default btn-small">Remover</a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        {!! $clients->render() !!}
    </div>
@endsection