app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

use Illuminate\Http\Request;

Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix'=>'admin','as'=>'admin.','middleware'=>'auth.checkrole:admin'],function (){
    Route::get('categories', ['uses'=>'CategoriesController@index','as'=>'categories.index']);
    Route::get('categories/create', ['uses'=>'CategoriesController@create','as'=>'categories.create']);
    Route::post('categories/store', ['uses'=>'CategoriesController@store','as'=>'categories.store']);
    Route::get('categories/edit/{id}', ['uses'=>'CategoriesController@edit','as'=>'categories.edit']);
    Route::post('categories/update/{id}', ['uses'=>'CategoriesController@update','as'=>'categories.update']);
    Route::get('categories/destroy/{id}', ['uses'=>'CategoriesController@destroy','as'=>'categories.destroy']);

    Route::get('products', ['uses'=>'ProductsController@index','as'=>'products.index']);
    Route::get('products/create', ['uses'=>'ProductsController@create','as'=>'products.create']);
    Route::post('products/store', ['uses'=>'ProductsController@store','as'=>'products.store']);
    Route::get('products/edit/{id}', ['uses'=>'ProductsController@edit','as'=>'products.edit']);
    Route::post('products/update/{id}', ['uses'=>'ProductsController@update','as'=>'products.update']);
    Route::get('products/destroy/{id}', ['uses'=>'ProductsController@destroy','as'=>'products.destroy']);

    Route::get('clients', ['uses'=>'ClientsController@index','as'=>'clients.index']);
    Route::get('clients/create', ['uses'=>'ClientsController@create','as'=>'clients.create']);
    Route::post('clients/store', ['uses'=>'ClientsController@store','as'=>'clients.store']);
    Route::get('clients/edit/{id}', ['uses'=>'ClientsController@edit','as'=>'clients.edit']);
    Route::post('clients/update/{id}', ['uses'=>'ClientsController@update','as'=>'clients.update']);
    Route::get('clients/destroy/{id}', ['uses'=>'ClientsController@destroy','as'=>'clients.destroy']);

    Route::get('orders', ['uses'=>'OrdersController@index','as'=>'orders.index']);
    Route::get('orders/{id}', ['uses'=>'OrdersController@edit','as'=>'orders.edit']);
    Route::post('orders/{id}', ['uses'=>'OrdersController@update','as'=>'orders.update']);

    Route::get('cupoms', ['uses'=>'CupomsController@index','as'=>'cupoms.index']);
    Route::get('cupoms/create', ['uses'=>'CupomsController@create','as'=>'cupoms.create']);
    Route::post('cupoms/store', ['uses'=>'CupomsController@store','as'=>'cupoms.store']);
});

Route::group(['prefix'=>'customer','middleware'=>'auth.checkrole:client','as'=>'customer.'], function (){
    Route::get('orders',['uses'=>'CheckoutController@index','as'=>'orders.index']);
    Route::get('orders/create',['uses'=>'CheckoutController@create','as'=>'orders.create']);
    Route::post('orders/store',['uses'=>'CheckoutController@store','as'=>'orders.store']);
});

Route::group(['middleware'=>'cors'],function (){

    Route::post('oauth/access_token', function() {
        return Response::json(Authorizer::issueAccessToken());
    });

    Route::group(['prefix'=>'api','middleware'=>'oauth','as'=>'api.'], function (){
        Route::group(['prefix'=>'client','middleware'=>'oauth.checkrole:client','as'=>'client.'], function () {
            Route::resource('orders', 'Api\Client\ClientCheckoutController', ['except'=> ['create','edit','destroy']]);
            Route::get('products','Api\Client\ClientProductController@index');
        });

        Route::group(['prefix'=>'deliveryman','middleware'=>'oauth.checkrole:deliveryman','as'=>'deliveryman.'], function () {
            Route::resource('orders', 'Api\Deliveryman\DeliverymanCheckoutController', ['except'=> ['create','edit','destroy']]);
            Route::patch('orders/{id}/update-status',[
                'uses'=>'Api\Deliveryman\DeliverymanCheckoutController@updateStatus','as'=>'orders.update_status'
            ]);
        });

        Route::get('authenticated',['uses' => 'Api\UserController@getAuthenticatedUser', 'as' => 'user.authenticated']);
    });

    Route::group(['prefix'=>'api','as'=>'api.'], function (){
        Route::post('/register',['uses' => 'Api\UserController@registerUser', 'as' => 'user.register']);
        Route::post('/password-reminder',['uses' => 'Api\UserController@sendPasswordResetToken', 'as'=> 'user.password-reminder']);
        Route::post('/password-reset',['uses' => 'Api\UserController@resetPassword', 'as'=> 'user.password-reset']);
    });
    
});

app/Models/Category.php
<?php

namespace CodeDelivery\Models;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Category extends Model implements Transformable
{
    use TransformableTrait;

    protected $fillable = [
        'name'
    ];

    public function products()
    {
        return $this->hasMany(Product::class);
    }

}

app/Http/Controllers/CategoriesController.php
<?php

namespace CodeDelivery\Http\Controllers;

use CodeDelivery\Http\Requests\AdminCategoryRequest;
use CodeDelivery\Repositories\CategoryRepository;
use CodeDelivery\Http\Requests;
use CodeDelivery\Services\CategoryService;

class CategoriesController extends Controller
{
    private $repository;
    private $service;

    public function __construct(CategoryRepository $repository, CategoryService $service)
    {
        $this->repository = $repository;
        $this->service = $service;
    }

    public function index()
    {
        $categories = $this->repository->paginate();
        return view('admin.categories.index',compact('categories'));
    }

    public function create()
    {
        return view('admin.categories.create');
    }
    
    public function store(AdminCategoryRequest $request)
    {
        $data = $request->all();
        $this->repository->create($data);

        return redirect()->route('admin.categories.index');
    }
    
    public function edit($id)
    {
        $category = $this->repository->find($id);
        return view('admin.categories.edit',compact('category'));
    }

    public function update(AdminCategoryRequest $request,$id)
    {
        $data = $request->all();
        $this->repository->update($data,$id);

        return redirect()->route('admin.categories.index');
    }

    public function destroy($id)
    {
        $response = $this->service->destroy($id);
        $redirect = redirect()->route('admin.categories.index');
        if (!$response['error']) {
            $redirect->with('message',$response['message']);
        } else {
            $redirect->with('error',$response['message']);
        }
        return $redirect;
    }
}

resources/views/admin/categories/_form.blade.php
<div class="form-group">
    {!! Form::label('Name','Nome:') !!}
    {!! Form::text('name', null, ['class'=>'form-control']) !!}
</div>

resources/views/admin/categories/create.blade.php
@extends('app')

@section('content')
    <div class="container">
        <h3>Nova categria</h3>

        @include('errors._check')

        {!! Form::open(['route'=>'admin.categories.store']) !!}

        @include('admin.categories._form')

        <div class="form-group">
            {!! Form::submit('Criar categoria',['class'=>'btn btn-primary']) !!}
        </div>

        {!! Form::close() !!}
    </div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('app')

@section('content')
    <div class="container">
        <h3>Editando categria: {{ $category->name }}</h3>

        @include('errors._check')

        {!! Form::model($category,['route'=>['admin.categories.update', $category->id]]) !!}

        @include('admin.categories._form')

        <div class="form-group">
            {!! Form::submit('Salvar categoria',['class'=>'btn btn-primary']) !!}
        </div>

        {!! Form::close() !!}
    </div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('app')

@section('content')
    <div class="container">
        <h3>Categorias</h3>
        @include('messages._check')
        <br>
        <a href="{{ route('admin.categories.create') }}" class="btn btn-default">Nova categoria</a>
        <br>
        <br>
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>ID</th>
                <th>Nome</th>
                <th>Ação</th>
            </tr>
            </thead>
            <tbody>
            @foreach($categories as $category)
                <tr>
                    <td>{{ $category->id }}</td>
                    <td>{{ $category->name }}</td>
                    <td>
                        <a href="{{ route('admin.categories.edit',['id'=>$category->id]) }}" class="btn btn-default btn-small">Editar</a>
                        <a href="{{ route('admin.categories.destroy',['id'=>$category->id]) }}" class="btn btn-default btn-small">Remover</a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        {!! $categories->render() !!}
    </div>
@endsection